# Taller Integrador — Módulo 1
## Máster en IA & Data Science | DevSeniorCode

**Nombre del estudiante:** Santiago Rodriguez Aguirre  
**Fecha de entrega:** 24 de marzo de 2026  
**Repositorio GitHub:** ___________________________

---

> Este taller evalúa todo lo visto en el Módulo 1:  
> Python · Pandas · Git & GitHub · Documentación

### ¿Cómo entregar?
1. Completa todas las celdas marcadas con 
2. Asegúrate de que el notebook corra sin errores (Kernel → Restart & Run All)
3. Sube el notebook y el CSV a tu repositorio de GitHub
4. Incluye un README.md con tu nombre y una descripción breve del proyecto

---

## Contexto del Dataset

Trabajarás con el dataset **`salud_mundial.csv`**, que contiene indicadores de salud de **159 países**.

| Columna | Descripción |
|---|---|
| `pais` | Nombre del país |
| `region` | Continente o región geográfica |
| `nivel_ingresos` | Nivel económico: Low, Medium, High, Very High |
| `esperanza_vida` | Esperanza de vida al nacer (años) |
| `gasto_salud_usd` | Gasto per cápita en salud (USD/año) |
| `mortalidad_infantil` | Muertes por cada 1,000 nacidos vivos |
| `medicos_por_1000` | Médicos por cada 1,000 habitantes |
| `poblacion_urbana_pct` | % de población que vive en zonas urbanas |
| `obesidad_pct` | % de la población con obesidad |
| `diabetes_pct` | % de la población con diabetes |
| `tabaquismo_pct` | % de fumadores |
| `camas_hospital_por_1000` | Camas hospitalarias por 1,000 hab. |
| `vacunacion_pct` | % de cobertura de vacunación |

---

---
## Parte 1 — Python Fundamental
### (30 puntos)

Antes de usar Pandas, demostraremos que dominas las estructuras básicas de Python.

---

### 1.1 — Listas y operaciones básicas

Tienes la siguiente lista con la esperanza de vida de 10 países (en años).

In [7]:
# Lista dada — NO modificar
esperanzas_de_vida = [72.3, 81.5, 60.1, 78.9, 55.4, 83.2, 67.8, 74.0, 49.3, 79.6]

**Ejercicio 1.1** — Usando Python puro (sin Pandas ni funciones built-in como `sum()` o `max()`):
- Calcula el **promedio** de la lista usando un bucle `for`
- Encuentra el **valor máximo** usando un bucle `for`
- Encuentra el **valor mínimo** usando un bucle `for`

In [13]:
# Tu código aquí
promedio = 0
valor_maximo = esperanzas_de_vida[0]
valor_minimo = esperanzas_de_vida[0]
# Promedio
for i in esperanzas_de_vida:
    promedio += i

promedio = promedio/len(esperanzas_de_vida)

# Máximo
for i in esperanzas_de_vida:
    if i > valor_maximo:
        valor_maximo = i

# Mínimo
for i in esperanzas_de_vida:
    if i < valor_minimo:
        valor_minimo = i

print(f"La esperanza de vida promedio de la lista es: {promedio:.2f}")
print(f"La esperanza de vida máxima es: {valor_maximo}")
print(f"La esperanza de vida mínima es: {valor_minimo}")

La esperanza de vida promedio de la lista es: 70.21
La esperanza de vida máxima es: 83.2
La esperanza de vida mínima es: 49.3

### 1.2 — Diccionarios

Los diccionarios son fundamentales en Data Science para representar registros.

**Ejercicio 1.2** — Crea un diccionario llamado `pais_info` que represente a Colombia con los siguientes campos:
- `nombre`: "Colombia"
- `region`: "Americas"  
- `esperanza_vida`: 76.5
- `gasto_salud_usd`: 560.3
- `nivel_ingresos`: "High"

Luego:
1. Imprime solo las **claves** del diccionario
2. Imprime solo los **valores**
3. Agrega un nuevo campo: `vacunacion_pct` con valor 82.1
4. Imprime el diccionario completo

In [14]:
# Tu código aquí

pais_info = {
    "nombre" : "Colombia",
    "region" : "Americas",
    "esperanza_vida" : 76.5,
    "gasto_salud_usd" : 560.3,
    "nivel_ingresos" : "High"
}

print(pais_info.keys())
print(pais_info.values())

#Agregando el campo nuevo
pais_info["vacunacion_pct"] = 82.1

print(f"El diccionario completo es: {pais_info}")

dict_keys(['nombre', 'region', 'esperanza_vida', 'gasto_salud_usd', 'nivel_ingresos'])
dict_values(['Colombia', 'Americas', 76.5, 560.3, 'High'])
El diccionario completo es: {'nombre': 'Colombia', 'region': 'Americas', 'esperanza_vida': 76.5, 'gasto_salud_usd': 560.3, 'nivel_ingresos': 'High', 'vacunacion_pct': 82.1}

### 1.3 — Funciones

Las funciones nos permiten reutilizar lógica.

**Ejercicio 1.3** — Crea una función llamada `clasificar_esperanza_vida` que reciba un número (años) y retorne:
- `"Alta"` si es >= 75
- `"Media"` si es entre 60 y 74.9
- `"Baja"` si es < 60

Prueba la función con al menos 5 valores distintos e imprime los resultados.

In [60]:
# Tu código aquí
def clasificar_esperanza_vida(anos):
    if anos < 60:
        return "Baja"
    elif anos>= 60 and anos <= 74.9:
        return "Media"
    elif anos >= 75:
        return "Alta"

prueba1 = clasificar_esperanza_vida(50)
prueba2 = clasificar_esperanza_vida(60)
prueba3 = clasificar_esperanza_vida(72)
prueba4 = clasificar_esperanza_vida(74.9)
prueba5 = clasificar_esperanza_vida(80)

print(f"Prueba 1: {prueba1}")
print(f"Prueba 2: {prueba2}")
print(f"Prueba 3: {prueba3}")
print(f"Prueba 4: {prueba4}")
print(f"Prueba 5: {prueba5}")

Prueba 1: Baja
Prueba 2: Media
Prueba 3: Media
Prueba 4: Media
Prueba 5: Alta

### 1.4 — Listas + Funciones + Bucles (integrador)

**Ejercicio 1.4** — Usa la función creada en 1.3 y la lista del ejercicio 1.1 para:
1. Crear una **nueva lista** llamada `clasificaciones` que contenga la clasificación de cada esperanza de vida
2. Imprimir cada par: `(valor, clasificación)` usando un bucle `for`

In [13]:
# Tu código aquí
clasificaciones = []

#Agregando la clasificación de cada esperanza de vida
for i in esperanzas_de_vida:
    clasificaciones.append(clasificar_esperanza_vida(i))

#Imprimiendo cada par
for i in range(len(esperanzas_de_vida)):
    print(f"({esperanzas_de_vida[i]}, {clasificaciones[i]})")

(72.3, Media)
(81.5, Alta)
(60.1, Media)
(78.9, Alta)
(55.4, Baja)
(83.2, Alta)
(67.8, Media)
(74.0, Media)
(49.3, Baja)
(79.6, Alta)

---
## Parte 2 — Análisis con Pandas
### (50 puntos)

---

### 2.1 — Carga y exploración inicial

🔧 **Ejercicio 2.1** — Importa Pandas y carga el archivo `salud_mundial.csv`.  
Luego ejecuta los comandos necesarios para responder:
1. ¿Cuántas filas y columnas tiene el dataset?
2. ¿Qué tipos de datos tiene cada columna?
3. ¿Cuántos valores nulos hay por columna?
4. Muestra las primeras 8 filas

In [8]:
# Tu código aquí
import pandas as pd

# Cargar el dataset
df = pd.read_csv('salud_mundial.csv')

# Dimensiones
print(f"La dimensión del dataset es {df.shape} \n")

# Tipos de datos
print("Tipos de datos")
df.info()
print("\n")
# Valores nulos
print("Valores nulos")
print(df.isnull().sum())
print("\n")

# Primeras 8 filas
df.head(8)

La dimensión del dataset es (159, 13)

Tipos de datos
<class 'pandas.DataFrame'>
RangeIndex: 159 entries, 0 to 158
Data columns (total 13 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   pais                     159 non-null    str
 1   region                   159 non-null    str
 2   nivel_ingresos           159 non-null    str
 3   esperanza_vida           155 non-null    float64
 4   gasto_salud_usd          154 non-null    float64
 5   mortalidad_infantil      149 non-null    float64
 6   medicos_por_1000         150 non-null    float64
 7   poblacion_urbana_pct     159 non-null    float64
 8   obesidad_pct             156 non-null    float64
 9   diabetes_pct             152 non-null    float64
 10  tabaquismo_pct           155 non-null    float64
 11  camas_hospital_por_1000  152 non-null    float64
 12  vacunacion_pct           155 non-null    float64
dtypes: float64(10), str(3)
memory usage: 16.3 KB


Valores nulos
pais                        0
region                      0
nivel_ingresos              0
esperanza_vida              4
gasto_salud_usd             5
mortalidad_infantil        10
medicos_por_1000            9
poblacion_urbana_pct        0
obesidad_pct                3
diabetes_pct                7
tabaquismo_pct              4
camas_hospital_por_1000     7
vacunacion_pct              4
dtype: int64

,pais,region,nivel_ingresos,esperanza_vida,gasto_salud_usd,mortalidad_infantil,medicos_por_1000,poblacion_urbana_pct,obesidad_pct,diabetes_pct,tabaquismo_pct,camas_hospital_por_1000,vacunacion_pct
0,Afghanistan,Asia,Low,60.9,18.4,NaN,0.19,40.8,15.2,9.2,10.1,1.0,41.1
1,Albania,Europe,Medium,65.1,673.8,28.1,1.18,45.0,27.2,9.7,17.3,1.2,84.5
2,Algeria,Africa,Medium,74.5,525.3,28.2,0.59,47.3,15.2,7.6,20.8,1.3,71.4
3,Angola,Africa,Low,NaN,37.1,54.7,0.79,37.4,13.4,7.8,28.2,1.6,48.7
4,Argentina,Americas,High,79.4,1809.5,7.6,NaN,71.5,18.9,10.1,33.0,3.4,81.7
5,Armenia,Europe,Medium,69.2,797.5,24.2,2.44,67.5,10.2,12.8,32.0,2.3,71.1
6,Australia,Oceania,Very High,NaN,9964.1,NaN,4.42,87.2,20.6,10.3,19.7,7.3,93.8
7,Austria,Europe,Very High,83.7,3685.2,3.9,2.71,91.0,31.0,5.9,18.6,6.0,90.9

### 2.2 — Limpieza de datos

🔧 **Ejercicio 2.2** — El dataset tiene algunos valores nulos (¡datos reales siempre tienen este problema!).  
1. Rellena los valores nulos de columnas **numéricas** con la **media** de cada columna
2. Verifica que ya no queden nulos
3. Explica en una celda de texto: ¿Por qué usamos la media y no simplemente eliminamos esas filas?

In [12]:
# Tu código aquí
df_nuevo = df

media_esperanza_vida = df_nuevo['esperanza_vida'].mean()
df_nuevo['esperanza_vida'] = df_nuevo['esperanza_vida'].fillna(media_esperanza_vida)

media_gasto_salud_usd = df_nuevo['gasto_salud_usd'].mean()
df_nuevo['gasto_salud_usd'] = df_nuevo['gasto_salud_usd'].fillna(media_gasto_salud_usd)

media_mortalidad_infantil = df_nuevo['mortalidad_infantil'].mean()
df_nuevo['mortalidad_infantil'] = df_nuevo['mortalidad_infantil'].fillna(media_mortalidad_infantil)

media_medicos_por_1000 = df_nuevo['medicos_por_1000'].mean()
df_nuevo['medicos_por_1000'] = df_nuevo['medicos_por_1000'].fillna(media_medicos_por_1000)

media_obesidad_pct = df_nuevo['obesidad_pct'].mean()
df_nuevo['obesidad_pct'] = df_nuevo['obesidad_pct'].fillna(media_obesidad_pct)

media_diabetes_pct = df_nuevo['diabetes_pct'].mean()
df_nuevo['diabetes_pct'] = df_nuevo['diabetes_pct'].fillna(media_diabetes_pct)

media_tabaquismo_pct = df_nuevo['tabaquismo_pct'].mean()
df_nuevo['tabaquismo_pct'] = df_nuevo['tabaquismo_pct'].fillna(media_tabaquismo_pct)

media_camas_hospital_por_1000 = df_nuevo['camas_hospital_por_1000'].mean()
df_nuevo['camas_hospital_por_1000'] = df_nuevo['camas_hospital_por_1000'].fillna(media_camas_hospital_por_1000)

media_vacunacion_pct = df_nuevo['vacunacion_pct'].mean()
df_nuevo['vacunacion_pct'] = df_nuevo['vacunacion_pct'].fillna(media_vacunacion_pct)

df_nuevo.isnull().sum()

pais                       0
region                     0
nivel_ingresos             0
esperanza_vida             0
gasto_salud_usd            0
mortalidad_infantil        0
medicos_por_1000           0
poblacion_urbana_pct       0
obesidad_pct               0
diabetes_pct               0
tabaquismo_pct             0
camas_hospital_por_1000    0
vacunacion_pct             0
dtype: int64

**Responde aquí** (doble clic para editar):

*¿Por qué usamos la media para rellenar nulos en vez de eliminar las filas?*

> Tu respuesta: Se utliza el promedio porqué este valor no afecta de forma significativa la distribución de los datos, por ende, es mejor utilizar el promedio en vez de eliminarlos, obteniendo así un mayor volumen de datos.

### 2.3 — Estadísticas descriptivas

🔧 **Ejercicio 2.3**
1. Muestra el resumen estadístico completo del dataset
2. ¿Cuál es la esperanza de vida **promedio** mundial?
3. ¿Cuál es el país con **mayor** gasto en salud? ¿Y el de **menor**?
4. ¿Cuál es la **mediana** de la mortalidad infantil?

In [25]:
# Tu código aquí
#1
display(df_nuevo.describe())
print("\n")

#2
print(f"La esperanza de vida promedio mundial es: {df_nuevo['esperanza_vida'].mean()}")

#3
#mayor gasto en salud
print("Mayor gasto en salud")
display(df_nuevo[df_nuevo['gasto_salud_usd'] == df_nuevo['gasto_salud_usd'].max()])
print("\n")

#menor gasto en salud
print("Menor gasto en salud")
display(df_nuevo[df_nuevo['gasto_salud_usd'] == df_nuevo['gasto_salud_usd'].min()])
print("\n")

#4
print(f"La mediana de la mortalidad es: {df_nuevo['mortalidad_infantil'].median()}")

,esperanza_vida,gasto_salud_usd,mortalidad_infantil,medicos_por_1000,poblacion_urbana_pct,obesidad_pct,diabetes_pct,tabaquismo_pct,camas_hospital_por_1000,vacunacion_pct
count,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000,159.000000
mean,71.085806,2217.050000,28.924832,1.978333,58.635220,19.217308,8.843421,22.918065,3.047368,77.616774
std,8.597795,2910.158218,25.442740,1.479252,21.703028,7.145886,2.851086,7.440349,2.147001,15.473480
min,51.100000,18.400000,2.100000,0.030000,16.200000,5.100000,3.100000,8.000000,0.300000,40.300000
25%,65.100000,138.800000,5.900000,0.670000,42.850000,13.600000,6.850000,17.450000,1.300000,68.400000
50%,73.200000,663.000000,23.700000,1.910000,57.100000,19.217308,8.800000,22.700000,2.200000,80.000000
75%,78.850000,3104.900000,43.300000,2.965000,77.950000,24.800000,10.500000,28.600000,4.300000,89.750000
max,84.000000,10311.800000,95.000000,5.430000,96.800000,34.800000,15.000000,40.000000,8.500000,99.000000

La esperanza de vida promedio mundial es: 71.08580645161291
Mayor gasto en salud

,pais,region,nivel_ingresos,esperanza_vida,gasto_salud_usd,mortalidad_infantil,medicos_por_1000,poblacion_urbana_pct,obesidad_pct,diabetes_pct,tabaquismo_pct,camas_hospital_por_1000,vacunacion_pct
153,Slovakia,Europe,Very High,82.2,10311.8,2.1,4.6,95.7,27.6,8.9,13.4,3.047368,97.7

Menor gasto en salud

,pais,region,nivel_ingresos,esperanza_vida,gasto_salud_usd,mortalidad_infantil,medicos_por_1000,poblacion_urbana_pct,obesidad_pct,diabetes_pct,tabaquismo_pct,camas_hospital_por_1000,vacunacion_pct
0,Afghanistan,Asia,Low,60.9,18.4,28.924832,0.19,40.8,15.2,9.2,10.1,1.0,41.1

La mediana de la mortalidad es: 23.7

### 2.4 — Filtrado y selección

🔧 **Ejercicio 2.4**
1. Filtra los países de **América** (`region == "Americas"`) y muestra solo las columnas: `pais`, `esperanza_vida`, `gasto_salud_usd`
2. Filtra los países con esperanza de vida **mayor a 80 años** — ¿cuántos son? ¿De qué regiones son?
3. Filtra los países con **nivel_ingresos == "Low"** y calcula su promedio de `mortalidad_infantil`
4. ¿Cuántos países tienen vacunación por encima del 90%?

In [ ]:
# Tu código aquí
#1
df_america = df_nuevo[df_nuevo['region'] == "Americas"]
df_america[['pais', 'esperanza_vida', 'gasto_salud_usd']]

                    pais  esperanza_vida  gasto_salud_usd
4              Argentina       79.400000          1809.50
11               Bolivia       75.800000           322.40
12                Brazil       74.100000          2913.70
16                Canada       78.900000          4019.60
17                 Chile       79.200000           854.50
19              Colombia       75.200000          2133.70
21            Costa Rica       76.300000          1772.80
23                  Cuba       78.900000          1804.20
26    Dominican Republic       71.085806           591.40
27               Ecuador       69.200000           638.80
29           El Salvador       71.900000           216.20
36             Guatemala       65.000000           442.80
37                 Haiti       51.200000            37.40
38              Honduras       74.200000           523.90
47               Jamaica       74.300000           279.50
59                Mexico       79.800000          2600.50
66             Nicaragua       74.900000           442.30
71                Panama       75.000000          1640.10
72              Paraguay       69.800000          2217.05
73                  Peru       72.700000           240.20
103        United States       81.200000          7230.70
104              Uruguay       78.400000          2744.30
106            Venezuela       73.600000           357.20
139               Guyana       65.700000           663.00
155             Suriname       66.700000           766.70
158  Trinidad and Tobago       77.800000          1157.80

In [ ]:
#2
df_filtrado2 = df_nuevo[df_nuevo['esperanza_vida'] > 80]
display(df_filtrado2.head())
print(f"El número de paises con esperanza de vida mayor a 80 es de: {len(df_filtrado2)}")
print(f"Las regiones con esperanza de vida mayor a 80 son: \n{df_filtrado2['region']}")

,pais,region,nivel_ingresos,esperanza_vida,gasto_salud_usd,mortalidad_infantil,medicos_por_1000,poblacion_urbana_pct,obesidad_pct,diabetes_pct,tabaquismo_pct,camas_hospital_por_1000,vacunacion_pct
7,Austria,Europe,Very High,83.7,3685.2,3.9,2.71,91.0,31.0,5.9,18.6,6.0,90.900000
10,Belgium,Europe,Very High,80.5,5228.4,3.0,5.27,83.1,32.6,8.9,10.9,8.5,97.200000
24,Czech Republic,Europe,Very High,82.6,7170.4,4.5,3.32,73.9,22.9,6.9,15.8,6.0,89.500000
25,Denmark,Europe,Very High,83.4,7672.6,4.8,5.07,91.1,24.5,5.0,16.3,7.1,77.616774
35,Greece,Europe,Very High,81.6,9325.9,2.9,4.07,83.3,25.5,11.0,27.8,4.7,94.800000

El número de paises con esperanza de vida mayor a 80 es de: 23
Las regiones con esperanza de vida mayor a 80 son:
7        Europe
10       Europe
24       Europe
25       Europe
35       Europe
44       Europe
45         Asia
46       Europe
52         Asia
64       Europe
76       Europe
87         Asia
88       Europe
101        Asia
102      Europe
103    Americas
114      Europe
116      Europe
129        Asia
136      Europe
142      Europe
148      Europe
153      Europe
Name: region, dtype: str

In [ ]:
#3
df_filtrado3 = df_nuevo[df_nuevo['nivel_ingresos'] == 'Low']
promedio_mortalidad_infantil = df_filtrado3['mortalidad_infantil'].mean()
display(df_filtrado3.head())
print(f"El promedio de mortalidad infantil es: {promedio_mortalidad_infantil:.2f}")

,pais,region,nivel_ingresos,esperanza_vida,gasto_salud_usd,mortalidad_infantil,medicos_por_1000,poblacion_urbana_pct,obesidad_pct,diabetes_pct,tabaquismo_pct,camas_hospital_por_1000,vacunacion_pct
0,Afghanistan,Asia,Low,60.900000,18.4,28.924832,0.19,40.8,15.2,9.2,10.1,1.0,41.1
3,Angola,Africa,Low,71.085806,37.1,54.700000,0.79,37.4,13.4,7.8,28.2,1.6,48.7
9,Bangladesh,Asia,Low,59.700000,78.8,81.000000,0.65,21.7,6.5,6.0,18.2,1.0,67.7
14,Cambodia,Asia,Low,60.400000,148.3,72.500000,0.03,43.6,9.5,7.6,30.5,0.4,44.4
15,Cameroon,Africa,Low,65.400000,129.2,28.924832,0.35,24.7,5.1,8.4,23.3,0.7,68.2

El promedio de mortalidad infantil es: 63.03

In [ ]:
#4
df_filtrado4 = df_nuevo[df_nuevo['vacunacion_pct'] > 90.0]
display(df_filtrado4.head())
print(f"El número de paises con un porcentaje de vacunación superior al 90% es de: {len(df_filtrado4)}")

,pais,region,nivel_ingresos,esperanza_vida,gasto_salud_usd,mortalidad_infantil,medicos_por_1000,poblacion_urbana_pct,obesidad_pct,diabetes_pct,tabaquismo_pct,camas_hospital_por_1000,vacunacion_pct
6,Australia,Oceania,Very High,71.085806,9964.1,28.924832,4.42,87.2,20.6,10.3,19.7,7.3,93.8
7,Austria,Europe,Very High,83.700000,3685.2,3.900000,2.71,91.0,31.0,5.9,18.6,6.0,90.9
10,Belgium,Europe,Very High,80.500000,5228.4,3.000000,5.27,83.1,32.6,8.9,10.9,8.5,97.2
17,Chile,Americas,High,79.200000,854.5,12.400000,2.16,80.3,27.0,12.0,31.2,2.9,91.4
23,Cuba,Americas,High,78.900000,1804.2,13.000000,2.84,81.7,23.9,12.7,32.8,4.1,90.2

El número de paises con un porcentaje de vacunación superior al 90% es de: 39

### 2.5 — Agrupaciones

🔧 **Ejercicio 2.5** — Usa `groupby()` para:
1. Calcular la **esperanza de vida promedio** por `region`
2. Calcular el **gasto en salud promedio** por `nivel_ingresos`
3. Calcular el **número de países** por región
4. ¿Qué región tiene la mayor esperanza de vida promedio? ¿Y la menor?

In [46]:
# Tu código aquí
df_nuevo.groupby('region')['esperanza_vida'].mean()

region
Africa      63.513623
Americas    73.472531
Asia        70.704762
Europe      77.651950
Oceania     68.746452
Name: esperanza_vida, dtype: float64

In [47]:
#2
df_nuevo.groupby('nivel_ingresos')['gasto_salud_usd'].mean()

nivel_ingresos
High         2003.016000
Low           126.881522
Medium        593.864894
Very High    6553.350000
Name: gasto_salud_usd, dtype: float64

In [ ]:
#3
df_nuevo.groupby('region')['pais'].count()

region
Africa      43
Americas    26
Asia        42
Europe      44
Oceania      4
Name: pais, dtype: int64

In [58]:
#4
region_esperanza_vida_max = df_nuevo.groupby('region')['esperanza_vida'].mean().idxmax()
region_esperanza_vida_min = df_nuevo.groupby('region')['esperanza_vida'].mean().idxmin()

print(f"La región con la mayor esperanza de vida promedio es: {region_esperanza_vida_max}")
print(f"La región con la menor esperanza de vida promedio es: {region_esperanza_vida_min}")

La región con la mayor esperanza de vida promedio es: Europe
La región con la menor esperanza de vida promedio es: Africa

### 2.6 — Nueva columna calculada

🔧 **Ejercicio 2.6**
1. Crea una nueva columna llamada `categoria_vida` aplicando la función `clasificar_esperanza_vida` que creaste en la Parte 1 a la columna `esperanza_vida`
2. ¿Cuántos países caen en cada categoría? (usa `value_counts()`)
3. ¿Qué porcentaje del total representa cada categoría?

In [75]:
# Tu código aquí
print(df.shape)
df_nuevo['categoria_vida'] = df_nuevo['esperanza_vida'].apply(clasificar_esperanza_vida)
display(df_nuevo.head())

paises_por_categoria = df_nuevo['categoria_vida'].value_counts()
paises_por_categoria_pct = df_nuevo['categoria_vida'].value_counts(normalize=True) *100


print(f"La cantidad de paises por categoria es")
print(paises_por_categoria, "\n")

print(f"La cantidad de paises por categoria en porcentaje es")
print(paises_por_categoria_pct)

(159, 14)

,pais,region,nivel_ingresos,esperanza_vida,gasto_salud_usd,mortalidad_infantil,medicos_por_1000,poblacion_urbana_pct,obesidad_pct,diabetes_pct,tabaquismo_pct,camas_hospital_por_1000,vacunacion_pct,categoria_vida
0,Afghanistan,Asia,Low,60.900000,18.4,28.924832,0.190000,40.8,15.2,9.2,10.1,1.0,41.1,Media
1,Albania,Europe,Medium,65.100000,673.8,28.100000,1.180000,45.0,27.2,9.7,17.3,1.2,84.5,Media
2,Algeria,Africa,Medium,74.500000,525.3,28.200000,0.590000,47.3,15.2,7.6,20.8,1.3,71.4,Media
3,Angola,Africa,Low,71.085806,37.1,54.700000,0.790000,37.4,13.4,7.8,28.2,1.6,48.7,Media
4,Argentina,Americas,High,79.400000,1809.5,7.600000,1.978333,71.5,18.9,10.1,33.0,3.4,81.7,Alta

La cantidad de paises por categoria es
categoria_vida
Media    79
Alta     63
Baja     17
Name: count, dtype: int64

La cantidad de paises por categoria en porcentaje es
categoria_vida
Media    49.685535
Alta     39.622642
Baja     10.691824
Name: proportion, dtype: float64

### 2.7 — Análisis libre (desafío)

**Ejercicio 2.7 (Opcional — puntos extra)** — Formula **una pregunta propia** sobre el dataset y respóndela con código.  

Ejemplos de preguntas que podrías hacer:
- ¿Existe relación entre el gasto en salud y la esperanza de vida?
- ¿Los países con más médicos tienen menor mortalidad infantil?
- ¿Qué región tiene mayor tasa de obesidad?

**Escribe tu pregunta:**

¿Cúal es la esperanza de vida promedio en función del nivel de ingreso?

In [76]:
# Tu código aquí
df_nuevo.groupby('nivel_ingresos')['esperanza_vida'].mean()

nivel_ingresos
High         76.564000
Low          60.358387
Medium       70.625230
Very High    80.309064
Name: esperanza_vida, dtype: float64

---
## Parte 3 — Git & GitHub
### (20 puntos)

Esta parte se evalúa por el **estado real de tu repositorio** en GitHub.  
Documenta los comandos que usaste respondiendo las preguntas en las celdas de texto.

---

### 3.1 — Configuración del repositorio

**Responde** (doble clic para editar):

**¿Qué comandos usaste para crear e inicializar tu repositorio local?**
```bash
# Tu respuesta: 
mkdir taller_modulo1
cd taller_modulo1
git init

```

**¿Cómo conectaste tu repositorio local con GitHub?**
```bash
# Tu respuesta: 
Se conecta a través del siguiente comando
git remote add origin https://github.com/santiagorodriag14/Master_IA.git


```

### 3.2 — Flujo de trabajo

**Responde:**

**¿Qué comando usaste para añadir los archivos al staging area?**
```bash
# Tu respuesta:
git add .

```

**¿Qué mensaje de commit escribiste? ¿Por qué elegiste ese mensaje?**
```bash
# Tu respuesta:
git commit -m "Taller modulo 1 completo - Master AI - DevSenior"

Lo seleccione para que quede explicito que hay en esos archivos

```

**¿Cómo subiste los cambios a GitHub?**
```bash
# Tu respuesta:
git add 'taller_modulo1'
git commit -m "Taller modulo 1 curso Master AI - DevSenior"
git push

```

### 3.3 — Buenas prácticas

**Responde:**

**¿Qué archivos debería incluir un `.gitignore` en un proyecto de Data Science? Menciona al menos 3 y explica por qué.**

> Tu respuesta: Entornos virtuales para evitar descargar librerias innecesarias; caché de python para evitar subir los datos de caché generados al ejecutar el programa, evitando ensuciar el historial de Git; Variables de entornos para no subir información sensible y quede abierta al público en GitHub

**¿Cuál es la diferencia entre `git add .` y `git add nombre_archivo`?**

> Tu respuesta: git add . añade todos los archivos nuevos o que han sido editados, en cambio, git 'nombre_archivo' sube ese archivo en específico.

---
## Parte 4 — Documentación (README)
### (Evaluada en GitHub)

Tu repositorio debe tener un archivo `README.md` que incluya:

- [ ] Título del proyecto
- [ ] Tu nombre
- [ ] Descripción del dataset (qué contiene, cuántos países, fuente)
- [ ] Cómo ejecutar el notebook (instrucciones paso a paso)
- [ ] Al menos 3 hallazgos o conclusiones del análisis
- [ ] Tecnologías usadas (Python, Pandas, Jupyter, Git)

---

### Checklist de entrega

Antes de hacer tu commit final, verifica:

- [ ] El notebook corre completo sin errores (Kernel → Restart & Run All)
- [ ] Todas las celdas están completadas
- [ ] Las celdas de texto tienen tus respuestas
- [ ] El archivo `salud_mundial.csv` está en el repositorio
- [ ] El `README.md` está completo
- [ ] El link al repositorio está en la celda de portada

---

## Criterios de evaluación

| Sección | Puntos |
|---|---|
| Parte 1 — Python | 30 |
| Parte 2 — Pandas | 50 |
| Parte 3 — Git | 20 |
| README en GitHub | 10 |
| Ejercicio libre 2.7 | +10 |
| **Total** | **110** |